.TH DEBIAN-RELEASE-INFO "1" "December 2009" "debian-release-info" "User Commands"
.SH NAME
debian-release-info \- provides information about Debian's releases
.SH SYNOPSIS
.B debian-release-info
[\fIOPTIONS\fR] \fIVERSION\fR
.SH OPTIONS
.TP
\fB\-\-date\fR
date for calculating the version (default: today)
.TP
\fB\-h\fR, \fB\-\-help\fR
display this help and exit
.SH "VERSION"
.TP
\fB\-a\fR, \fB\-\-all\fR
list all known versions
.TP
\fB\-d\fR, \fB\-\-devel\fR
latest development version
.TP
\fB\-o\fR, \fB\-\-old\fR
latest old (stable) version
.TP
\fB\-s\fR, \fB\-\-stable\fR
latest stable version
.TP
\fB\-\-supported\fR
list of all supported stable versions
.TP
\fB\-t\fR, \fB\-\-testing\fR
latest testing version
.TP
\fB\-\-unsupported\fR
list of all unsupported stable versions
.SH AUTHOR
The script and this manual page was written by
Benjamin Drung <bdrung@ubuntu.com>.
