.TH RELEASE-INFO "1" "December 2009" "release-info" "User Commands"
.SH NAME
release-info \- provides information about the distributions' releases
.SH SYNOPSIS
.B release-info
[\fIOPTIONS\fR] \fIVERSION\fR
.SH DESCRIPTION
.B release-info
is a symlink to the release-info command of your distribution. On Debian it links to
.B debian-release-info
and on Ubuntu it links to
.B ubuntu-release-info.
All options, which are described in this manual page, are available in all
.B release-info
commands. All other options, which are not described here, are distribution
specific.
.SH OPTIONS
.TP
\fB\-\-date\fR
date for calculating the version (default: today)
.TP
\fB\-h\fR, \fB\-\-help\fR
display this help and exit
.SH "VERSION"
.TP
\fB\-a\fR, \fB\-\-all\fR
list all known versions
.TP
\fB\-d\fR, \fB\-\-devel\fR
latest development version
.TP
\fB\-s\fR, \fB\-\-stable\fR
latest stable version
.TP
\fB\-\-supported\fR
list of all supported stable versions
.TP
\fB\-\-unsupported\fR
list of all unsupported stable versions
.SH SEE ALSO
debian-release-info(1), ubuntu-release-info(1)
.SH AUTHOR
The script and this manual page was written by
Benjamin Drung <bdrung@ubuntu.com>.
